### ISSUE TITLE
学习英文标记语言成了负担？

### ISSUE THREAD

**Issue by nonusx** [itorr/e#10]
![image](https://user-images.githubusercontent.com/60562136/106830800-be2cd180-66c9-11eb-945b-f3c8bd48c305.png)

**Comment by nobodxbodon** [comment]
《[Coding Is for Everyone—as Long as You Speak English](https://www.wired.com/story/coding-is-for-everyoneas-long-as-you-speak-english/)》

友人新开的项目：https://gitee.com/laowu2019_admin/Chinese_HTML 欢迎串门

**Comment by nonusx** [comment]
呵呵，学你这个倒是真的成了负担
