### ISSUE TITLE
特性请求：“闭合任意标签”【。】能力

### ISSUE THREAD

**Issue by Artoria2e5** [itorr/e#4]
HTML4 中，存在由 SGML 继承而来的 `</>` “闭合前一个打开的标签” 标识符。如果易网页也能有一个类似的就好了。

**Comment by Artoria2e5** [comment]
看上去加上了【。】 at f4f44eb

**Comment by itorr** [comment]
@Arthur2e5 感谢提交建议！网络不是太好，刚刚加了`【。】` 和 `【、】` 还没有确认到文档中关于 `</>` 的部分，所以还没有回应。如果能提供下文档中关于 `</>` 特性的片段那最好不过了！

**Comment by Artoria2e5** [comment]
这你不能看 w3c HTML4 定义，要看它（严格意义）基于的 SGML：
https://en.wikipedia.org/wiki/Standard_Generalized_Markup_Language#SHORTTAG
（SGML 的 Markup Minimization 很多，毕竟当时也是为了能像 Markdown 一样很流畅地写的，结果后来出了个 HTML 和（去除大部分人类优化）XML，大家各种塞东西（于是不得不搞 well-formness），到最后 HTML5 直接……）
（哦对了，很多别的 Minimization 也可以学一下）

w3c 也写过这篇 blog 介绍：
https://www.w3.org/blog/2007/10/shorttags/

**Comment by Artoria2e5** [comment]
哦，HTML 标准的话，
https://www.w3.org/TR/html401/appendix/notes.html#h-B.3.7

**Comment by itorr** [comment]
@Arthur2e5 感谢指导！又学习到了好多，我把这部分引用到相关修正说明中
